ALTER TABLE usuarios ENGINE=InnoDB;

CREATE TABLE criptomonedas (
    id_criptomoneda INT AUTO_INCREMENT PRIMARY KEY,
    ticker VARCHAR(5) NOT NULL UNIQUE,
    precio_actual DECIMAL(18,8) NOT NULL,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;